# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ZZTVShow' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZZTVShow
    pod 'pop', '~> 1.0.12'
  target 'ZZTVShowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZZTVShowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
